### ISSUE TITLE
Injectdylib won't work

### ISSUE THREAD

**Issue by anonymouz4** [huku-/injectdso#1]
I didn't test it on older versions, but on newer version it fails, the reason is the following:

Finding the Mach Header for DYLINKER works.
But it can't find the `dyld_all_image_infos` location.
Maybe `DYLD_ALL_IMAGE_INFOS_OFFSET_OFFSET` is not correct on newer versions or 64bit mach-o.

That would at least explain why Apple removed 
`#define DYLD_ALL_IMAGE_INFOS_OFFSET_OFFSET 0x1010` from `mach-o/dyld_images.h`.

---
```
read_memory(task, address + daii_offset, &daii, sizeof(struct dyld_all_image_infos));
```
doesn't return a valid `dyld_all_image_infos struct`. Therefore everything afterwards will fail, since `daii.infoArrayCount` will be 0.

**Comment by anonymouz4** [comment]
The code has many more problems and flaws, so I'll close this issue and fix it myself

**Comment by huku-** [comment]
Indeed, injectdylib was last tested long time ago. If you change your mind, feel free to elaborate more on the problems and flaws and/or submit a pull request.

**Comment by anonymouz4** [comment]
I got it to work right now on 10.15. But a pull request won't be helpful, since my code structure is completely different and my assembly code too, bc I'm executing other things, not dlopen() and I wrote it in Intel syntax, not AT&T. the main problem in this project is:

---
1) the symbol lookup in the remote task isn't working, I'm currently also trying to find a good way (I thought I had the same shared library cache as my task and could therefore just resolve it locally but I was wrong)

2) the injected code won't work, since you create and launch a mach thread and then try to properly setup as pthread with the func `_pthread_set_self(NULL)`. While that worked before 10.14, apple changed  the function and you can't call it with `NULL`. I solved this by calling `pthread_create_from_mach_thread()` and creating another, properly setup pthread that will run all the code I need.
